"""Render human-readable teacher/student reasoning traces → docs/REASONING_TRACES.md.

For each chosen case, prints the teacher (Claude) FIRACO reasoning spine, then GPT-5's
and Llama-3B's attempts at the SAME case, then exactly what L-GED "saw" (missed teacher
nodes by weight, hallucinations with reason, dropped edges, misgroundings). The point is
to make the summary statistics legible: you can read *why* Llama's L-GED is large.

Run under the trustworthy (embedding) alignment so the annotations match the paper:
    LEX_DRL_SIMILARITY=embedding poetry run python scripts/build_traces_doc.py
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

os.environ.setdefault("LEX_DRL_SIMILARITY", "embedding")

import lex_drl.alignment as alignment_module  # noqa: E402
from lex_drl.alignment import align_all  # noqa: E402
from lex_drl.discrepancy import compute_discrepancies  # noqa: E402
from lex_drl.schema import LegalReasoningGraph  # noqa: E402

GRAPHS = Path("data/outputs/graphs")
OUT = Path("docs/REASONING_TRACES.md")

# Cases to render, with a one-line human framing.
CASES = {
    "E2": "Easy — NYC hospital promotion tool (Local Law 144, AEDT bias audit).",
    "H2": "Hard — multi-jurisdiction deployment (NYC + Colorado + Texas).",
}
STUDENTS = [("gpt5", "GPT-5 (frontier student)"), ("llama3_2b", "Llama-3.2-3B (weak student)")]


def _load(p: Path) -> LegalReasoningGraph:
    return LegalReasoningGraph.model_validate_json(p.read_text())


def _clip(s: str, n: int = 100) -> str:
    s = " ".join(str(s).split())
    return s if len(s) <= n else s[: n - 1] + "…"


def _spine(g: LegalReasoningGraph, *, issues=6, rules=8, apps=3, obl=4) -> list[str]:
    """Readable FIRACO 'spine' of a graph — the reasoning, not the JSON."""
    L: list[str] = []
    L.append(f"- **Issues framed ({len(g.issues)}):**")
    for i in g.issues[:issues]:
        L.append(f"  - {i.iid}: {_clip(i.label, 110)}")
    if len(g.issues) > issues:
        L.append(f"  - …+{len(g.issues) - issues} more")
    L.append(f"- **Rules cited ({len(g.rules)}):**")
    for r in g.rules[:rules]:
        L.append(f"  - {r.rid} `{_clip(r.citation, 55)}` — {_clip(r.label, 70)} *({r.authority.value})*")
    if len(g.rules) > rules:
        L.append(f"  - …+{len(g.rules) - rules} more")
    L.append(f"- **Application ({len(g.applications)} steps):**")
    for a in g.applications[:apps]:
        L.append(f"  - {a.aid} [{a.result.value}] {_clip(a.reasoning, 100)}")
    if len(g.applications) > apps:
        L.append(f"  - …+{len(g.applications) - apps} more")
    concl = "; ".join(f"{c.cid}={c.determination.value}/{c.confidence.value}" for c in g.conclusions) or "—"
    L.append(f"- **Conclusions ({len(g.conclusions)}):** {concl}")
    L.append(f"- **Obligations ({len(g.obligations)}):**")
    for o in g.obligations[:obl]:
        L.append(f"  - {o.oid}: {_clip(o.label, 90)} *({o.status.value})*")
    if len(g.obligations) > obl:
        L.append(f"  - …+{len(g.obligations) - obl} more")
    return L


def _counts(g: LegalReasoningGraph) -> str:
    return (f"F{len(g.facts)} I{len(g.issues)} R{len(g.rules)} A{len(g.applications)} "
            f"C{len(g.conclusions)} O{len(g.obligations)} · E{len(g.edges)} · **{g.node_count()} nodes**")


def _annotate(teacher, student, label) -> list[str]:
    rep = compute_discrepancies(teacher, student, align_all(teacher, student))
    L: list[str] = []
    L.append(f"**What L-GED saw — {label}:**  "
             f"missed {rep.v_miss_count} · hallucinated {rep.v_halluc_count} · "
             f"dropped/mismatched edges {rep.e_diff_count} · misgrounded rules {rep.v_misground_count} · "
             f"**L-GED = {rep.l_ged:.1f}** *(lower = closer to teacher)*")
    L.append("")
    top_miss = sorted(rep.v_miss, key=lambda m: m.weight, reverse=True)[:6]
    if top_miss:
        L.append("- *Highest-cost teacher nodes it missed:* "
                 + "; ".join(f"{m.teacher_id}(w{m.weight:g}) {_clip(m.label, 55)}" for m in top_miss))
    halluc = rep.v_halluc[:6]
    if halluc:
        L.append("- *Nodes it invented (not in teacher):* "
                 + "; ".join(f"{h.student_id} {_clip(h.label, 45)} [{h.reason}]" for h in halluc))
    if rep.v_misground:
        L.append("- *Right idea, wrong/authority citation:* "
                 + "; ".join(f"{mg.student_id}: cited `{_clip(mg.student_citation,28)}` vs teacher "
                             f"`{_clip(mg.teacher_citation,28)}`" for mg in rep.v_misground[:4]))
    return L


def main() -> None:
    assert alignment_module.SIMILARITY_METHOD == "embedding", (
        f"run with LEX_DRL_SIMILARITY=embedding (got {alignment_module.SIMILARITY_METHOD})")

    L: list[str] = []
    L.append("<!-- Generated by scripts/build_traces_doc.py — readable teacher/student "
             "reasoning traces behind the L-GED numbers. For Prof. Rao. -->")
    L.append("")
    L.append("# Reasoning Traces — Teacher vs. Students")
    L.append("")
    L.append("Companion to the summary stats: a few **actual FIRACO reasoning traces** so you can "
             "see *what is happening* behind each L-GED score. The teacher (Claude) writes the "
             "reference analysis; each student attempts the **same** case; L-GED counts what the "
             "student missed, invented, or mis-connected relative to the teacher.")
    L.append("")
    L.append("**How to read a trace:** each analysis is a graph — **F**acts → **I**ssues → **R**ules "
             "→ **A**pplication → **C**onclusion → **O**bligations. Below we show the *spine* (issues, "
             "rules, application, conclusion, obligations); facts and edges are summarized in the counts.")
    L.append("")

    for case, framing in CASES.items():
        teacher = _load(GRAPHS / f"{case}_reference.json")
        L.append("---")
        L.append("")
        L.append(f"## Case {case} — {framing}")
        L.append("")
        # at-a-glance
        L.append("**At a glance (graph size):**")
        L.append("")
        L.append("| | Teacher (Claude) | GPT-5 | Llama-3B |")
        L.append("|---|---|---|---|")
        gpt = _load(GRAPHS / f"{case}_agent_gpt5.json")
        llama = _load(GRAPHS / f"{case}_agent_llama3_2b.json")
        L.append(f"| node counts | {_counts(teacher)} | {_counts(gpt)} | {_counts(llama)} |")
        L.append("")
        L.append(f"> The weak student collapses a rich analysis into a stub: **{len(llama.issues)} issue, "
                 f"{len(llama.applications)} application step, {len(llama.conclusions)} conclusion, "
                 f"{len(llama.obligations)} obligation** — vs the teacher's "
                 f"{len(teacher.issues)} issues / {len(teacher.applications)} application steps / "
                 f"{len(teacher.obligations)} obligations. That gap *is* the L-GED.")
        L.append("")

        # teacher spine
        L.append("### 🧑‍🏫 Teacher (Claude) — the reference reasoning")
        L.append("")
        L.extend(_spine(teacher))
        L.append("")

        # students
        for key, slabel in STUDENTS:
            g = _load(GRAPHS / f"{case}_agent_{key}.json")
            icon = "🟢" if key == "gpt5" else "🔴"
            L.append(f"### {icon} {slabel}")
            L.append("")
            L.extend(_spine(g))
            L.append("")
            L.extend(_annotate(teacher, g, slabel))
            L.append("")

    # ── patch demo: Llama H2 baseline vs patched k3 (clean store) ──
    patched_p = GRAPHS / "H2_agent_llama3_2b_patched_clean_k3.json"
    if patched_p.exists():
        teacher = _load(GRAPHS / "H2_reference.json")
        base = _load(GRAPHS / "H2_agent_llama3_2b.json")
        patched = _load(patched_p)
        L.append("---")
        L.append("")
        L.append("## Bonus — what a *patch* does to a trace (Llama, H2, k=3, clean store)")
        L.append("")
        L.append("Same weak student, same case, but with the top-3 verified 'POLICY REASONING NOTES' "
                 "prepended. This is the intervention the whole project is testing.")
        L.append("")
        rb = compute_discrepancies(teacher, base, align_all(teacher, base))
        rp = compute_discrepancies(teacher, patched, align_all(teacher, patched))
        L.append("| | no-patch baseline | + top-3 patches |")
        L.append("|---|---|---|")
        L.append(f"| graph size | {_counts(base)} | {_counts(patched)} |")
        L.append(f"| L-GED | {rb.l_ged:.1f} | {rp.l_ged:.1f} |")
        L.append(f"| missed / halluc / edges | {rb.v_miss_count} / {rb.v_halluc_count} / {rb.e_diff_count} "
                 f"| {rp.v_miss_count} / {rp.v_halluc_count} / {rp.e_diff_count} |")
        L.append("")
        delta = rp.l_ged - rb.l_ged
        L.append(f"Net L-GED change: **{delta:+.1f}** "
                 f"({'patches helped' if delta < 0 else 'patches did not help'}). "
                 "Read the two spines above/below to see it is mostly edge-count movement, "
                 "not the weak student suddenly recovering the teacher's missing rules — which is "
                 "exactly the Phase-3 caveat.")
        L.append("")
        L.append("**Patched student spine:**")
        L.append("")
        L.extend(_spine(patched))
        L.append("")

    # ── takeaways ──
    L.append("---")
    L.append("")
    L.append("## What these traces reveal (why the numbers look the way they do)")
    L.append("")
    L.append("1. **The weak student under-generates.** Llama-3B frames **1 issue** and writes **1 "
             "application step** where the teacher frames 7–9 issues and 12–16 steps. Its large L-GED "
             "is almost entirely `v_miss` (46–63 missed teacher nodes), *not* hallucination — it "
             "doesn't say wrong things, it says almost nothing.")
    L.append("2. **The frontier student reasons in parallel, not identically.** GPT-5's spine tracks "
             "the teacher's (same issues, same violations, similar obligations) but is more compact "
             "and rephrases — which is exactly why *meaning-based* node matching (Phase 1) is "
             "essential: word-overlap would wrongly score GPT-5's paraphrases as misses/hallucinations.")
    L.append("3. **You can see the contamination in a trace.** In **E2**, the teacher cites a "
             "**fabricated `§20-875`** (R7) for civil penalties; GPT-5 cites the *real* **`§20-872`** "
             "— and L-GED charges *GPT-5* with the misgrounding. The 'ground truth' is wrong here, "
             "which is the Phase-3 finding made concrete. (Llama also wanders off-jurisdiction in E2 — "
             "citing Colorado and Texas statutes on an NYC-only fact pattern.)")
    L.append("4. **A patch nudges grounding, not coverage.** In the H2 patch demo, the top-3 notes "
             "flip Llama's lead rule from the wrong `NYC LL 144` to the correct `CO AIA §6-1-1703` "
             "and trim a stray edge (L-GED −4.5) — but the student still frames only 1 issue. The "
             "intervention corrects *what little it writes*; it does not make a 3B model write the "
             "other 60 nodes. That ceiling is the case for the Tier-3 'learn from the teacher' "
             "direction in `IMPROVEMENT_DIRECTIONS.md`.")
    L.append("")

    OUT.write_text("\n".join(L))
    print(f"wrote {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    main()
